services:
  - type: web
    name: nuv-growth
    env: static
    buildCommand: yarn install && yarn build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: no-referrer-when-downgrade
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /manifest.json
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /sw.js
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
